# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  run-liquibase:
    docker:
      - image: liquibase/liquibase:latest

    steps:
      - checkout
      - run:
          name: "Run Liquibase Quality Checks"
          command: |
            "liquibase --version"
            "liquibase --changeLogFile=main.xml checks run"

workflows:
  liquibase-qc-workflow:
    jobs:
      - run-liquibase
