# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  inspect_db_code:
    docker:
      - image: liquibase/liquibase:latest

    steps:
      - checkout
      - run:
          name: "Run Liquibase version"
          command: "liquibase --version"

      - run: 
          name: "Run Liquibase Quality Checks"
          command: "liquibase --changeLogFile=main.xml checks run"
  
  deploy_dev_db:
    docker:
      - image: liquibase/liquibase:4.10.0
    steps:
    - checkout
    - run:
        name: "Run database changes against dev database"
        command: echo "liquibase update"
  
  build_app:
    docker:
      - image: maven:3.3-jdk-8
    steps:
    - checkout
    - run:
        name: "Build app changes"
        command: echo "building app changes"


workflows:
  ci_workflow:
    jobs:
      - inspect_db_code
      - deploy_dev_db
      - build_app
