# This is a basic workflow to help you get started with Actions

name: run_changes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
       

env:
    LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
    LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_COMMAND_URL }}
    LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_COMMAND_USERNAME }}
    LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}
    LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
    LIQUIBASE_CLASSPATH: ${{ secrets.LIQUIBASE_CLASSPATH }}
    
jobs:

  Build_Job:
    runs-on: self-hosted
    environment: 
      name: DEV

    steps:
    - name: Running Quality Checks
      uses: actions/checkout@v2
    - run: |
        tree
        ls
        liquibase checks run

#     - name: Running Quality Checks
#       uses: docker://liquibase/liquibase
#       with:
#         args: checks run
        
#     - name: Reviewing pending SQL changes
#       uses: docker://liquibase/liquibase
#       with:
#         args: status --verbose --log-level=info
    
#     - name: Validating Database Changes
#       uses: docker://liquibase/liquibase
#       with:
#         args: update
      
#     - name: Validating rollbacks
#       uses: docker://liquibase/liquibase
#       with:
#         args: rollbackOneUpdate --force
        
#     - name: Deploying Database Changes
#       uses: docker://liquibase/liquibase
#       with:
#         args: update
          
    
#   Test_Job:
#     needs: Build_Job
#     runs-on: ubuntu-latest
#     environment: 
#       name: TEST

#     steps:
#     - uses: actions/checkout@v2
    
#     - name: Deploying Database Changes
#       uses: docker://liquibase/liquibase
#       with:
#         args: update
                

#   Deploy_Prod_Job:
#     needs: Test_Job
#     runs-on: ubuntu-latest
#     environment: 
#       name: PROD

#     steps:
#     - uses: actions/checkout@v2
        
#     - name: Deploying Database Changes
#       uses: docker://liquibase/liquibase
#       with:
#         args: update
        
