name: rollback_changes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
   inputs:
     deploymentID:
       description: 'Enter a deploymentID to rollback'
       required: true

env:
    LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
    LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_COMMAND_URL }}
    LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_COMMAND_USERNAME }}
    LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}
    LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
    LIQUIBASE_CLASSPATH: ${{ secrets.LIQUIBASE_CLASSPATH }}
    
jobs:

  Build_Job:
    runs-on: ubuntu-latest
    environment: 
      name: DEV

    steps: 
    - uses: actions/checkout@v2
    
    - name: Rolling back DEV changes
      uses: docker://liquibase/liquibase:latest
      with:
        args: rollbackOneUpdate --deploymentID=${{ github.event.inputs.deploymentID }} --force
    
    - name: Runnig the History command 
      uses: docker://liquibase/liquibase:snowflake
      with:
        args: liquibase history
          
  Test_Job:
    needs: Build_Job
    runs-on: ubuntu-latest
    environment: 
      name: TEST

    steps: 
    - uses: actions/checkout@v2
    
    - name: Rolling back TEST changes
    - run: |
        echo Rolling back TEST changes
          
  Deploy_Prod_Job:
    needs: Test_Job
    runs-on: ubuntu-latest
    environment: 
      name: PROD

    steps: 
    - uses: actions/checkout@v2

    - name: Rolling back PROD changes
    - run: |
        echo Rolling back PROD changes
    

